#!/bin/sh

SCRIPT_FOLDER="$HOME/.scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
	touch $SCRIPT_FILE
else
	echo '#!/bin/sh' > $SCRIPT_FILE
	chmod 0755 $SCRIPT_FILE
	v $SCRIPT_FILE
fi
