#!/bin/bash

CONFIG_FOLDER="$HOME/.config"
DOTFILES_BACKUP_FOLDER="$HOME/Documents/Projects/dotFiles"

rsync -r $CONFIG_FOLDER/i3 $DOTFILES_BACKUP_FOLDER/
rsync -r $CONFIG_FOLDER/neofetch $DOTFILES_BACKUP_FOLDER/
rsync -r $CONFIG_FOLDER/nvim $DOTFILES_BACKUP_FOLDER/
rsync -r $CONFIG_FOLDER/ranger $DOTFILES_BACKUP_FOLDER/
rsync -r $HOME/.scripts $DOTFILES_BACKUP_FOLDER/
rsync $HOME/.bashrc $DOTFILES_BACKUP_FOLDER/
rsync $HOME/.newsboat/config $DOTFILES_BACKUP_FOLDER/.newsboat/config
rsync $HOME/.newsboat/urls $DOTFILES_BACKUP_FOLDER/.newsboat/urls
rsync $CONFIG_FOLDER/USBGuard/usbguard-applet-qt.conf $DOTFILES_BACKUP_FOLDER
rsync $HOME/.zshrc $DOTFILES_BACKUP_FOLDER/
rsync $CONFIG_FOLDER/redshift/redshift.conf $DOTFILES_BACKUP_FOLDER/redshift/redshift.conf
rsync -r $CONFIG_FOLDER/polybar $DOTFILES_BACKUP_FOLDER/
rsync $HOME/.Xresources $DOTFILES_BACKUP_FOLDER/
