#!/bin/bash
# this script will compile or run another finishing operation on a document. via vim

#compiles: md

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd $dir || exit

textype() { \
	command="pdflatex"
	( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"
	$command --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" >/dev/null &&
	biber --input-directory "$dir" "$base" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
}

case $file in 
	*\.md) pandoc "$file" --pdf-engine=xelatex -o "$base".pdf;;
esac
