#!/bin/sh

if [ -f /tmp/recordingicon ]; then

	ICON = $(cat /tmp/recordingicon)
	if [ -f /tmp/recordingpid ]; then
		if [ "$ICON" ]; then
			echo %{F#FF0000}$ICON%{F-}
		fi
	else
		echo ""
	fi
else
	echo ""
fi
