#!/bin/sh

IFACE=$(ifconfig | grep tun0 | awk '{print $1}')

if [ "$IFACE" = "tun0:" ]; then
	echo   "%{F#00FF00} VPN  $(wget http://ipecho.net/plain -O - -q | xargs geoiplookup | awk '{print $4}' | cut -f1 -d ',')%{F-}"
else
    echo "%{F#FF0000} VPN DISCONNECTED%{F-}"
fi
